var horses = [{"name":"Alpha", "url":"https://en.wikipedia.org/wiki/2012_Kentucky_Derby", "type":"horse"},
{"name":"Adonis", "url":"https://en.wikipedia.org/wiki/1999_Kentucky_Derby", "type":"horse"},
{"name":"Afternoon Deelites", "url":"https://en.wikipedia.org/wiki/1995_Kentucky_Derby", "type":"horse"},
{"name":"Air Forbes Won", "url":"https://en.wikipedia.org/wiki/1982_Kentucky_Derby", "type":"horse"},
{"name":"Althea", "url":"https://en.wikipedia.org/wiki/1984_Kentucky_Derby", "type":"horse"},
{"name":"Always Dreaming", "url":"https://en.wikipedia.org/wiki/Always_Dreaming", "type":"horse"},
{"name":"Any Given Saturday", "url":"https://en.wikipedia.org/wiki/Any_Given_Saturday", "type":"horse"},
{"name":"Atswhatimtalknbout", "url":"https://en.wikipedia.org/wiki/2003_Kentucky_Derby", "type":"horse"},
{"name":"Backtalk", "url":"https://en.wikipedia.org/wiki/Backtalk_(horse)", "type":"horse"},
{"name":"Bear Hunt", "url":"https://en.wikipedia.org/wiki/1984_Kentucky_Derby", "type":"horse"},
{"name":"Badger Land", "url":"https://en.wikipedia.org/wiki/1986_Kentucky_Derby", "type":"horse"},
{"name":"Bedouin", "url":"https://en.wikipedia.org/wiki/1984_Kentucky_Derby", "type":"horse"},
{"name":"Balto Star", "url":"https://en.wikipedia.org/wiki/2001_Kentucky_Derby", "type":"horse"},
{"name":"Big Truck", "url":"https://en.wikipedia.org/wiki/Big_Truck", "type":"horse"},
{"name":"Birdstone", "url":"https://en.wikipedia.org/wiki/Birdstone", "type":"horse"},
{"name":"Blow Out", "url":"https://en.wikipedia.org/wiki/1996_Kentucky_Derby", "type":"horse"},
{"name":"Brian's Time", "url":"https://en.wikipedia.org/wiki/Brian%27s_Time", "type":"horse"},
{"name":"Bolo", "url":"https://en.wikipedia.org/wiki/2015_Kentucky_Derby", "type":"horse"},
{"name":"Built For Pleasure", "url":"https://en.wikipedia.org/wiki/1996_Kentucky_Derby", "type":"horse"},
{"name":"Casual Lies", "url":"https://en.wikipedia.org/wiki/1992_Kentucky_Derby", "type":"horse"},
{"name":"Caveat", "url":"https://en.wikipedia.org/wiki/Caveat_(horse)", "type":"horse"},
{"name":"Chefs", "url":"https://en.wikipedia.org/wiki/1988_Kentucky_Derby", "type":"horse"},
{"name":"Chilito", "url":"https://en.wikipedia.org/wiki/1998_Kentucky_Derby", "type":"horse"},
{"name":"Chumming", "url":"https://en.wikipedia.org/wiki/1983_Kentucky_Derby", "type":"horse"},
{"name":"Classic Go Go", "url":"https://en.wikipedia.org/wiki/1981_Kentucky_Derby", "type":"horse"},
{"name":"Crimson Classic", "url":"https://en.wikipedia.org/wiki/1997_Kentucky_Derby", "type":"horse"},
{"name":"Coax Me Chad", "url":"https://en.wikipedia.org/wiki/1984_Kentucky_Derby", "type":"horse"},
{"name":"Concerto", "url":"https://en.wikipedia.org/wiki/1997_Kentucky_Derby", "type":"horse"},
{"name":"Dance Floor", "url":"https://en.wikipedia.org/wiki/Dance_Floor_(horse)", "type":"horse"},
{"name":"Disposal", "url":"https://en.wikipedia.org/wiki/1992_Kentucky_Derby", "type":"horse"},
{"name":"Domestic Dispute", "url":"https://en.wikipedia.org/wiki/2003_Kentucky_Derby", "type":"horse"},
{"name":"Double Sonic", "url":"https://en.wikipedia.org/wiki/1981_Kentucky_Derby", "type":"horse"},
{"name":"Dr. Bobby A.", "url":"https://en.wikipedia.org/wiki/1990_Kentucky_Derby", "type":"horse"},
{"name":"Dullahan", "url":"https://en.wikipedia.org/wiki/Dullahan_(horse)", "type":"horse"},
{"name":"Eight Belles", "url":"https://en.wikipedia.org/wiki/Eight_Belles", "type":"horse"},
{"name":"El Baba", "url":"https://en.wikipedia.org/wiki/1982_Kentucky_Derby", "type":"horse"},
{"name":"Encolure", "url":"https://en.wikipedia.org/wiki/1985_Kentucky_Derby", "type":"horse"},
{"name":"Fast and Accurate", "url":"https://en.wikipedia.org/wiki/2017_Kentucky_Derby", "type":"horse"},
{"name":"Forty Niner", "url":"https://en.wikipedia.org/wiki/Forty_Niner_(horse)", "type":"horse"},
{"name":"Freezing Rain", "url":"https://en.wikipedia.org/wiki/1983_Kentucky_Derby", "type":"horse"},
{"name":"Frosted", "url":"https://en.wikipedia.org/wiki/Frosted_(horse)", "type":"horse"},
{"name":"Fusaichi Pegasus", "url":"https://en.wikipedia.org/wiki/Fusaichi_Pegasus", "type":"horse"},
{"name":"Gato Del Sol", "url":"https://en.wikipedia.org/wiki/Gato_Del_Sol", "type":"horse"},
{"name":"General Challenge", "url":"https://en.wikipedia.org/wiki/1999_Kentucky_Derby", "type":"horse"},
{"name":"Genuine Risk", "url":"https://en.wikipedia.org/wiki/Genuine_Risk", "type":"horse"},
{"name":"Going Wild", "url":"https://en.wikipedia.org/wiki/2005_Kentucky_Derby", "type":"horse"},
{"name":"Girvin", "url":"https://en.wikipedia.org/wiki/Girvin", "type":"horse"},
{"name":"Grindstone", "url":"https://en.wikipedia.org/wiki/Grindstone_(horse)", "type":"horse"},
{"name":"Groovy", "url":"https://en.wikipedia.org/wiki/Groovy_(horse)", "type":"horse"},
{"name":"Gulch", "url":"https://en.wikipedia.org/wiki/Gulch_(horse)", "type":"horse"},
{"name":"Habano", "url":"https://en.wikipedia.org/wiki/1981_Kentucky_Derby", "type":"horse"},
{"name":"Happy Jazz Band", "url":"https://en.wikipedia.org/wiki/1991_Kentucky_Derby", "type":"horse"},
{"name":"Hello", "url":"https://en.wikipedia.org/wiki/1997_Kentucky_Derby", "type":"horse"},
{"name":"Hence", "url":"https://en.wikipedia.org/wiki/2017_Kentucky_Derby", "type":"horse"},
{"name":"Highland Park", "url":"https://en.wikipedia.org/wiki/1983_Kentucky_Derby", "type":"horse"},
{"name":"I Am the Game", "url":"https://en.wikipedia.org/wiki/1985_Kentucky_Derby", "type":"horse"},
{"name":"Irap", "url":"https://en.wikipedia.org/wiki/2017_Kentucky_Derby", "type":"horse"},
{"name":"Imawildandcrazyguy", "url":"https://en.wikipedia.org/wiki/2007_Kentucky_Derby", "type":"horse"},
{"name":"International Star", "url":"https://en.wikipedia.org/wiki/2015_Kentucky_Derby", "type":"horse"},
{"name":"Jim's Orbit", "url":"https://en.wikipedia.org/wiki/1988_Kentucky_Derby", "type":"horse"},
{"name":"Killer Diller", "url":"https://en.wikipedia.org/wiki/1990_Kentucky_Derby", "type":"horse"},
{"name":"Laoban", "url":"https://en.wikipedia.org/wiki/2016_Kentucky_Derby", "type":"horse"},
{"name":"Land Rush", "url":"https://en.wikipedia.org/wiki/1990_Kentucky_Derby", "type":"horse"},
{"name":"Laser Light", "url":"https://en.wikipedia.org/wiki/1982_Kentucky_Derby", "type":"horse"},
{"name":"Lawyer Ron", "url":"https://en.wikipedia.org/wiki/Lawyer_Ron", "type":"horse"},
{"name":"Liquidity", "url":"https://en.wikipedia.org/wiki/2007_Kentucky_Derby", "type":"horse"},
{"name":"Lion Heart", "url":"https://en.wikipedia.org/wiki/2004_Kentucky_Derby", "type":"horse"},
{"name":"Lone Star Sky", "url":"https://en.wikipedia.org/wiki/2003_Kentucky_Derby", "type":"horse"},
{"name":"Majesto", "url":"https://en.wikipedia.org/wiki/2016_Kentucky_Derby", "type":"horse"},
{"name":"Master Plan", "url":"https://en.wikipedia.org/wiki/2017_Kentucky_Derby", "type":"horse"},
{"name":"McCraken", "url":"https://en.wikipedia.org/wiki/2017_Kentucky_Derby", "type":"horse"},
{"name":"Mister Frisky", "url":"https://en.wikipedia.org/wiki/Mister_Frisky", "type":"horse"},
{"name":"Mogambo", "url":"https://en.wikipedia.org/wiki/Mogambo_(horse)", "type":"horse"},
{"name":"Monarchos", "url":"https://en.wikipedia.org/wiki/Monarchos", "type":"horse"},
{"name":"Mr. Z", "url":"https://en.wikipedia.org/wiki/2015_Kentucky_Derby", "type":"horse"},
{"name":"My Mac", "url":"https://en.wikipedia.org/wiki/1983_Kentucky_Derby", "type":"horse"},
{"name":"Nobiz Like Shobiz", "url":"https://en.wikipedia.org/wiki/Nobiz_Like_Shobiz", "type":"horse"},
{"name":"No More Flowers", "url":"https://en.wikipedia.org/wiki/1987_Kentucky_Derby", "type":"horse"},
{"name":"Ocho Ocho Ocho", "url":"https://en.wikipedia.org/wiki/2015_Kentucky_Derby", "type":"horse"},
{"name":"Orb", "url":"https://en.wikipedia.org/wiki/Orb_(horse)", "type":"horse"},
{"name":"On the Line", "url":"https://en.wikipedia.org/wiki/1987_Kentucky_Derby", "type":"horse"},
{"name":"Outwork", "url":"https://en.wikipedia.org/wiki/2016_Kentucky_Derby", "type":"horse"},
{"name":"Oxbow", "url":"https://en.wikipedia.org/wiki/Oxbow_(horse)", "type":"horse"},
{"name":"Mission Impazible", "url":"https://en.wikipedia.org/wiki/2010_Kentucky_Derby", "type":"horse"},
{"name":"Parfaitement", "url":"https://en.wikipedia.org/wiki/1983_Kentucky_Derby", "type":"horse"},
{"name":"Partez", "url":"https://en.wikipedia.org/wiki/1981_Kentucky_Derby", "type":"horse"},
{"name":"Pass the Tab", "url":"https://en.wikipedia.org/wiki/1981_Kentucky_Derby", "type":"horse"},
{"name":"Patch", "url":"https://en.wikipedia.org/wiki/2017_Kentucky_Derby", "type":"horse"},
{"name":"Paulrus", "url":"https://en.wikipedia.org/wiki/1991_Kentucky_Derby", "type":"horse"},
{"name":"Pistols and Roses", "url":"https://en.wikipedia.org/wiki/Pistols_and_Roses", "type":"horse"},
{"name":"Pulpit", "url":"https://en.wikipedia.org/wiki/1997_Kentucky_Derby", "type":"horse"},
{"name":"Pyro", "url":"https://en.wikipedia.org/wiki/Pyro_(horse)", "type":"horse"},
{"name":"Quintana", "url":"https://en.wikipedia.org/wiki/1991_Kentucky_Derby", "type":"horse"},
{"name":"Request for Parole", "url":"https://en.wikipedia.org/wiki/2002_Kentucky_Derby", "type":"horse"},
{"name":"Revolutionary", "url":"https://en.wikipedia.org/wiki/2013_Kentucky_Derby", "type":"horse"},
{"name":"Rockamundo", "url":"https://en.wikipedia.org/wiki/1993_Kentucky_Derby", "type":"horse"},
{"name":"Rock and Roll", "url":"https://en.wikipedia.org/wiki/1998_Kentucky_Derby", "type":"horse"},
{"name":"Rockwall", "url":"https://en.wikipedia.org/wiki/1982_Kentucky_Derby", "type":"horse"},
{"name":"Risen Star", "url":"https://en.wikipedia.org/wiki/Risen_Star", "type":"horse"},
{"name":"Sabercat", "url":"https://en.wikipedia.org/wiki/2012_Kentucky_Derby", "type":"horse"},
{"name":"Scrimshaw", "url":"https://en.wikipedia.org/wiki/2003_Kentucky_Derby", "type":"horse"},
{"name":"Shawklit Won", "url":"https://en.wikipedia.org/wiki/1987_Kentucky_Derby", "type":"horse"},
{"name":"Skywalker", "url":"https://en.wikipedia.org/wiki/Skywalker_(horse)", "type":"horse"},
{"name":"So Vague", "url":"https://en.wikipedia.org/wiki/1984_Kentucky_Derby", "type":"horse"},
{"name":"Stay Thirsty", "url":"https://en.wikipedia.org/wiki/Stay_Thirsty", "type":"horse"},
{"name":"Stanford", "url":"https://en.wikipedia.org/wiki/2015_Kentucky_Derby", "type":"horse"},
{"name":"Stephen Got Even", "url":"https://en.wikipedia.org/wiki/1999_Kentucky_Derby", "type":"horse"},
{"name":"Street Sense", "url":"https://en.wikipedia.org/wiki/Street_Sense_(horse)", "type":"horse"},
{"name":"Summer Squall", "url":"https://en.wikipedia.org/wiki/Summer_Squall", "type":"horse"},
{"name":"Supah Blitz", "url":"https://en.wikipedia.org/wiki/2003_Kentucky_Derby", "type":"horse"},
{"name":"Swale", "url":"https://en.wikipedia.org/wiki/Swale_(horse)", "type":"horse"},
{"name":"Technology", "url":"https://en.wikipedia.org/wiki/1992_Kentucky_Derby", "type":"horse"},
{"name":"Thunder Snow", "url":"https://en.wikipedia.org/wiki/Thunder_Snow", "type":"horse"},
{"name":"Trojan Nation", "url":"https://en.wikipedia.org/wiki/2016_Kentucky_Derby", "type":"horse"},
{"name":"Unbridled", "url":"https://en.wikipedia.org/wiki/Unbridled", "type":"horse"},
{"name":"Upstart", "url":"https://en.wikipedia.org/wiki/2015_Kentucky_Derby", "type":"horse"},
{"name":"Vinceremos", "url":"https://en.wikipedia.org/wiki/2014_Kentucky_Derby", "type":"horse"},
{"name":"War", "url":"https://en.wikipedia.org/wiki/1987_Kentucky_Derby", "type":"horse"},
{"name":"War Story", "url":"https://en.wikipedia.org/wiki/2015_Kentucky_Derby", "type":"horse"},
{"name":"We Miss Artie", "url":"https://en.wikipedia.org/wiki/2014_Kentucky_Derby", "type":"horse"},
{"name":"Wild Horses", "url":"https://en.wikipedia.org/wiki/2002_Kentucky_Derby", "type":"horse"},
{"name":"Woodchopper", "url":"https://en.wikipedia.org/wiki/1981_Kentucky_Derby", "type":"horse"},
{"name":"Volcano", "url":"https://en.wikipedia.org/wiki/1875_Kentucky_Derby", "type":"horse"},
{"name":"Ascension", "url":"https://en.wikipedia.org/wiki/1875_Kentucky_Derby", "type":"horse"},
{"name":"Vagabond", "url":"https://en.wikipedia.org/wiki/1875_Kentucky_Derby", "type":"horse"},
{"name":"Gold Mine", "url":"https://en.wikipedia.org/wiki/1875_Kentucky_Derby", "type":"horse"},
{"name":"Vagrant", "url":"https://en.wikipedia.org/wiki/Vagrant_(horse)", "type":"horse"},
{"name":"Day Star", "url":"https://en.wikipedia.org/wiki/Day_Star", "type":"horse"},
{"name":"Falsetto", "url":"https://en.wikipedia.org/wiki/Falsetto_(horse)", "type":"horse"},
{"name":"Getaway", "url":"https://en.wikipedia.org/wiki/1881_Kentucky_Derby", "type":"horse"},
{"name":"Apollo", "url":"https://en.wikipedia.org/wiki/Apollo_(horse)", "type":"horse"},
{"name":"Lost Cause", "url":"https://en.wikipedia.org/wiki/1882_Kentucky_Derby", "type":"horse"},
{"name":"Favor", "url":"https://en.wikipedia.org/wiki/1885_Kentucky_Derby", "type":"horse"},
{"name":"Masterpiece", "url":"https://en.wikipedia.org/wiki/1886_Kentucky_Derby", "type":"horse"},
{"name":"Autocrat", "url":"https://en.wikipedia.org/wiki/1888_Kentucky_Derby", "type":"horse"},
{"name":"Outlook", "url":"https://en.wikipedia.org/wiki/1890_Kentucky_Derby", "type":"horse"},
{"name":"Lookout", "url":"https://en.wikipedia.org/wiki/Lookout_(horse)", "type":"horse"},
{"name":"Mirage", "url":"https://en.wikipedia.org/wiki/1893_Kentucky_Derby", "type":"horse"},
{"name":"The Dragon", "url":"https://en.wikipedia.org/wiki/1896_Kentucky_Derby", "type":"horse"},
{"name":"Thrive", "url":"https://en.wikipedia.org/wiki/1900_Kentucky_Derby", "type":"horse"},
{"name":"Hindus", "url":"https://en.wikipedia.org/wiki/1900_Kentucky_Derby", "type":"horse"},
{"name":"Bad News", "url":"https://en.wikipedia.org/wiki/1903_Kentucky_Derby", "type":"horse"},
{"name":"Synchronized", "url":"https://en.wikipedia.org/wiki/1908_Kentucky_Derby", "type":"horse"},
{"name":"Bronzewing", "url":"https://en.wikipedia.org/wiki/1914_Kentucky_Derby", "type":"horse"},
{"name":"Watermelon", "url":"https://en.wikipedia.org/wiki/1914_Kentucky_Derby", "type":"horse"},
{"name":"Regret", "url":"https://en.wikipedia.org/wiki/Regret_(horse)", "type":"horse"},
{"name":"Double Eagle", "url":"https://en.wikipedia.org/wiki/1915_Kentucky_Derby", "type":"horse"},
{"name":"Skeptic", "url":"https://en.wikipedia.org/wiki/1917_Kentucky_Derby", "type":"horse"},
{"name":"Exterminator", "url":"https://en.wikipedia.org/wiki/Exterminator_(horse)", "type":"horse"},
{"name":"Upset", "url":"https://en.wikipedia.org/wiki/1920_Kentucky_Derby", "type":"horse"},
{"name":"Behave Yourself", "url":"https://en.wikipedia.org/wiki/Behave_Yourself_(horse)", "type":"horse"},
{"name":"Planet", "url":"https://en.wikipedia.org/wiki/1921_Kentucky_Derby", "type":"horse"},
{"name":"Martingale", "url":"https://en.wikipedia.org/wiki/1923_Kentucky_Derby", "type":"horse"},
{"name":"Vigil", "url":"https://en.wikipedia.org/wiki/1923_Kentucky_Derby", "type":"horse"},
{"name":"Enchantment", "url":"https://en.wikipedia.org/wiki/1923_Kentucky_Derby", "type":"horse"},
{"name":"Needle Gun", "url":"https://en.wikipedia.org/wiki/1925_Kentucky_Derby", "type":"horse"},
{"name":"Backbone", "url":"https://en.wikipedia.org/wiki/1925_Kentucky_Derby", "type":"horse"},
{"name":"Rock Man", "url":"https://en.wikipedia.org/wiki/1926_Kentucky_Derby", "type":"horse"},
{"name":"Rhinock", "url":"https://en.wikipedia.org/wiki/1926_Kentucky_Derby", "type":"horse"},
{"name":"Rip Rap", "url":"https://en.wikipedia.org/wiki/1927_Kentucky_Derby", "type":"horse"},
{"name":"Misstep", "url":"https://en.wikipedia.org/wiki/1928_Kentucky_Derby", "type":"horse"},
{"name":"Bar None", "url":"https://en.wikipedia.org/wiki/1928_Kentucky_Derby", "type":"horse"},
{"name":"Distraction", "url":"https://en.wikipedia.org/wiki/1928_Kentucky_Derby", "type":"horse"},
{"name":"Minotaur", "url":"https://en.wikipedia.org/wiki/1929_Kentucky_Derby", "type":"horse"},
{"name":"Paul Bunyan", "url":"https://en.wikipedia.org/wiki/1929_Kentucky_Derby", "type":"horse"},
{"name":"Chip", "url":"https://en.wikipedia.org/wiki/1929_Kentucky_Derby", "type":"horse"},
{"name":"Broadway Limited", "url":"https://en.wikipedia.org/wiki/1930_Kentucky_Derby", "type":"horse"},
{"name":"High Foot", "url":"https://en.wikipedia.org/wiki/1930_Kentucky_Derby", "type":"horse"},
{"name":"Boys Howdy", "url":"https://en.wikipedia.org/wiki/1931_Kentucky_Derby", "type":"horse"},
{"name":"Surf Board", "url":"https://en.wikipedia.org/wiki/1931_Kentucky_Derby", "type":"horse"},
{"name":"Economic", "url":"https://en.wikipedia.org/wiki/1932_Kentucky_Derby", "type":"horse"},
{"name":"Hoops", "url":"https://en.wikipedia.org/wiki/1932_Kentucky_Derby", "type":"horse"},
{"name":"Good Advice", "url":"https://en.wikipedia.org/wiki/1933_Kentucky_Derby", "type":"horse"},
{"name":"Mata Hari", "url":"https://en.wikipedia.org/wiki/Mata_Hari_(horse)", "type":"horse"},
{"name":"Quasimodo", "url":"https://en.wikipedia.org/wiki/1934_Kentucky_Derby", "type":"horse"},
{"name":"Today", "url":"https://en.wikipedia.org/wiki/1935_Kentucky_Derby", "type":"horse"},
{"name":"Grand Slam", "url":"https://en.wikipedia.org/wiki/1936_Kentucky_Derby", "type":"horse"},
{"name":"Dispose", "url":"https://en.wikipedia.org/wiki/1941_Kentucky_Derby", "type":"horse"},
{"name":"Swain", "url":"https://en.wikipedia.org/wiki/1941_Kentucky_Derby", "type":"horse"},
{"name":"Hollywood", "url":"https://en.wikipedia.org/wiki/1942_Kentucky_Derby", "type":"horse"},
{"name":"Bankrupt", "url":"https://en.wikipedia.org/wiki/1943_Kentucky_Derby", "type":"horse"},
{"name":"Jeep", "url":"https://en.wikipedia.org/wiki/1945_Kentucky_Derby", "type":"horse"},
{"name":"Assault", "url":"https://en.wikipedia.org/wiki/Assault_(horse)", "type":"horse"},
{"name":"Phalanx", "url":"https://en.wikipedia.org/wiki/Phalanx_(horse)", "type":"horse"},
{"name":"Cosmic Bomb", "url":"https://en.wikipedia.org/wiki/Cosmic_Bomb_(horse)", "type":"horse"},
{"name":"Bullet Proof", "url":"https://en.wikipedia.org/wiki/1947_Kentucky_Derby", "type":"horse"},
{"name":"Citation", "url":"https://en.wikipedia.org/wiki/Citation_(horse)", "type":"horse"},
{"name":"Wine List", "url":"https://en.wikipedia.org/wiki/1949_Kentucky_Derby", "type":"horse"},
{"name":"Stranded", "url":"https://en.wikipedia.org/wiki/1950_Kentucky_Derby", "type":"horse"},
{"name":"Counterpoint", "url":"https://en.wikipedia.org/wiki/Counterpoint_(horse)", "type":"horse"},
{"name":"Allied", "url":"https://en.wikipedia.org/wiki/1954_Kentucky_Derby", "type":"horse"},
{"name":"No Regrets", "url":"https://en.wikipedia.org/wiki/1956_Kentucky_Derby", "type":"horse"},
{"name":"Die Hard", "url":"https://en.wikipedia.org/wiki/1959_Kentucky_Derby", "type":"horse"},
{"name":"Stupendous", "url":"https://en.wikipedia.org/wiki/1966_Kentucky_Derby", "type":"horse"},
{"name":"Forward Pass", "url":"https://en.wikipedia.org/wiki/Forward_Pass_(horse)", "type":"horse"},
{"name":"Verbatim", "url":"https://en.wikipedia.org/wiki/1968_Kentucky_Derby", "type":"horse"},
{"name":"Unconscious", "url":"https://en.wikipedia.org/wiki/1971_Kentucky_Derby", "type":"horse"},
{"name":"Avatar", "url":"https://en.wikipedia.org/wiki/Avatar_(horse)", "type":"horse"},
{"name":"Nostalgia", "url":"https://en.wikipedia.org/wiki/1977_Kentucky_Derby", "type":"horse"},
{"name":"Toro", "url":"https://en.wikipedia.org/wiki/1928_Kentucky_Derby", "type":"both"},
{"name":"Nassau", "url":"https://en.wikipedia.org/wiki/1923_Kentucky_Derby", "type":"both"},
{"name":"Rampage", "url":"https://en.wikipedia.org/wiki/1986_Kentucky_Derby", "type":"both"},
{"name":"Dark Star", "url":"https://en.wikipedia.org/wiki/Dark_Star_(horse)", "type":"both"}
];



var frisbee = [{"name":"Absolute Zero", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=V3bGXF31rhKg5xzt7bYXx4sH6Ia%2b50vKw1XUdVUr0b8%3d", "type":"frisbee"},
{"name":"Adelphos", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=DFQF5z%2fRLSCrUd%2fSJNAvFtYvX1PHfVv6fSVMpBxyon8%3d", "type":"frisbee"},
{"name":"Air Show", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=2udFSr66Xia5fj9B45VDkh2GGBe2M5lqjuDa1QqwxYk%3d", "type":"frisbee"},
{"name":"AK Pipeline", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=iCEBpCo7KnDCzID4wo%2bkMhp48WM2Jff0g%2foz%2bRNDjiE%3d", "type":"frisbee"},
{"name":"Alchemy", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=mLe67zC9AfRH%2fwd1NaGpxzyvqfjCZJpXqzkmUee5hCU%3d", "type":"frisbee"},
{"name":"All Jeeps All Night", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=tGJ2coJIzKD%2bG3k7Urn6oLvMMA9JIn1LqMRZ6rGCjbk%3d", "type":"frisbee"},
{"name":"Allen's Army", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=Jd4Lwj5pZg%2fKksLsKyO0RVlfjYabefU7McVOTOIbOnE%3d", "type":"frisbee"},
{"name":"Alloy", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=BCfSCkaNHNIbixIpSrBK6oKYTpMeUq19oACHjInhlZg%3d", "type":"frisbee"},
{"name":"Ambiguous Grey", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=QFD%2frfN%2fuowEcBhfEj4Un76YjcOoeVKjALNIpsDMb3c%3d", "type":"frisbee"},
{"name":"American Barbecue", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=pDpiKLBXOtAjRtprOKCyGCyOfnIxEheUS3e1agp9TMs%3d", "type":"frisbee"},
{"name":"American Hyperbole", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=0Z1w5tklAiRqieIjvqBkaV2lGq5eQHQf6nEDupYZxxc%3d", "type":"frisbee"},
{"name":"All Outta Love", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=qe%2fH3hOGm3lBJ4alGvbVtz%2fmcnSFuyMy6QIcC913oNY%3d", "type":"frisbee"},
{"name":"Anchor", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=%2fkr2IXXvIK7559yw5Fk6VGcG0N5u78m8yOcPDoEmWEI%3d", "type":"frisbee"},
{"name":"Animals", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=MUql61MeHzqyYa0z12%2bF5cqhGxr73DMZc8oYBG8F2rk%3d", "type":"frisbee"},
{"name":"Argo", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=Z95wI%2fn2mYPjR%2bRzytIgqpYYGJ9GshQTSEx48XE%2b%2b10%3d", "type":"frisbee"},
{"name":"Asylum", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=2D7fc7YAaJ6qp1IbTd7vhOlgsZ6glKqbI2vrMokzYts%3d", "type":"frisbee"},
{"name":"Autonomous", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=%2bG3pOu6Nqci1p5WX%2bhauiLI6qGInJ3Pl4uit4YUYLCI%3d", "type":"frisbee"},
{"name":"Auxiliary", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=7MvCi5lV5rNzEuQPZTb%2bc1KDBohvdiL9B%2fcnY7CxsvA%3d", "type":"frisbee"},
{"name":"Balloon", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=YNpsgJnWYmG4A%2bg2%2fzrlj7YUBk5Awv%2fTmpf3tsat93E%3d", "type":"frisbee"},
{"name":"Barefoot", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=B4orbwmKnbXxLqPpCRuSxarklVaorvg%2biIZ%2bZOHs0gs%3d", "type":"frisbee"},
{"name":"Barracuda", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=VTWImeC18oO%2fQ%2bP58FUV6ChWePAF3H25aMIIF5NCwrs%3d", "type":"frisbee"},
{"name":"Battleship", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=hoYCLaGj6vCV3dPoV0nF1n3otJf7%2bYOBjWALg%2b6SJBA%3d", "type":"frisbee"},
{"name":"Bear Proof", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=MkpeoNr9gccqgjI1a2IJSmWzJiJImGE39QTjn9OVpR0%3d", "type":"frisbee"},
{"name":"Bird", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=9v6TWBm%2fDUX4Gb2jqaCJGQDt3caAYXrKfaV1%2bOrnMZg%3d", "type":"frisbee"},
{"name":"Birdfruit", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=5y1M8b0M9jAfQPuH1XP0gtE%2bmL%2fptHur3f3duJq3uak%3d", "type":"frisbee"},
{"name":"Big Rock", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=hTOfPWcIRRsndC0C0z1cVPBQJbN0j9G058Ix1NMzIDc%3d", "type":"frisbee"},
{"name":"Big Wrench", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=5Ei8tPKgWEW74si%2fKzrjD%2fHkMQj%2bx9ZAqIPUDkiyZ4c%3d", "type":"frisbee"},
{"name":"Big Sky", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=o%2bGgPMNU0YYyGgVhai44La5uQRSgsSFVZRHKDvmLt8I%3d", "type":"frisbee"},
{"name":"Bitmap", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=fHE%2fcu2Nj6dxQ4i0b1pBUyFMNBWAG0pMCG7K%2fk%2fZbpI%3d", "type":"frisbee"},
{"name":"Black Lung", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=KU0MqjxGmaMSOXGn1%2f95uD59I4xmW%2b%2bUPwKRclkyXLE%3d", "type":"frisbee"},
{"name":"Black Market", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=ppiulyNg%2bWp40A7OUr4%2fn56VsrEagpr%2frSvXZAzdXsI%3d", "type":"frisbee"},
{"name":"Blackbird", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=vbKzuNLGjAFiyc88d6wXrJn4r%2bD3KuKF4L7x9eqhA3U%3d", "type":"frisbee"},
{"name":"Blackfish", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=%2f6%2fc6yFBqWLLcGeBTQUWmFVnhLyOl5Rp20%2bW9LoOzkM%3d", "type":"frisbee"},
{"name":"Blade", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=o9w8h%2bBNiS34dKTKfbpBU6OGx1JvparC53tVPgIqbFQ%3d", "type":"frisbee"},
{"name":"Bophades", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=xDXOK56Mjmpomt2anP3%2biLTr142dgorBQg18XjnCkdc%3d", "type":"frisbee"},
{"name":"Boyshe", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=6FsyMr%2bW%2bzyNFP6TxfiNKI4VuG8lucPPS3CvH1w5fnc%3d", "type":"frisbee"},
{"name":"Blitzkrieg", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=aSzRihmE9x0JRRrjaJzZiVzR%2blJ0ggwZKkvVwDfWjo4%3d", "type":"frisbee"},
{"name":"Beachfront Property", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=2AG7CFcBbp%2fvzznq%2fsMDAXW%2bJ%2fNP5LJXughZfI3Ka5I%3d", "type":"frisbee"},
{"name":"Blueprint", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=w6IR7%2bBmHGR2lXnGyHNsoxmz%2b753jB4YB8%2bfltiGKdM%3d", "type":"frisbee"},
{"name":"Boston Baked Beans", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=9XQpxzDOp9zhjY07IqdnF4IDJLWWaULpBTa%2famdzeQg%3d", "type":"frisbee"},
{"name":"Bold City", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=aEIxK%2fMoSXmAGpgwOsZgPsgGOQd%2foBcUFAnvRLr14TE%3d", "type":"frisbee"},
{"name":"Brawl", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=BHHklYpa4v%2bmQ%2bEdDFkZP1Uwi1dU1fUT150FQLMFyLU%3d", "type":"frisbee"},
{"name":"Breakfast Club", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=3btvnjw95ymxi2e5ZayKSDhfhRwVkQP3sDGL9apqKKE%3d", "type":"frisbee"},
{"name":"Brooklyn Book Club", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=YE5Tz5FtQRUlo%2fgj8W6VM0nL3BN0LzHRwjTjX4P8j0Q%3d", "type":"frisbee"},
{"name":"Broad City", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=X%2fzqVlbLxHavrLMdhkw6chtFaG4NqVY%2bPlJWDx8QVVo%3d", "type":"frisbee"},
{"name":"Boxcar", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=K%2fR4ET5aP6ujxh%2bAiPYHILthw3H5o2uyt%2bWKM8V8O6A%3d", "type":"frisbee"},
{"name":"Bozos", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=6UIMN20aDdVIScIlZGfzbL7Glb6iBaHQBoT9NtaHDsU%3d", "type":"frisbee"},
{"name":"Buffalo Lake Effect", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=ff4OJp7pk%2bK8MAK7RZWtzv7AKsslSCENvjRYenS89Gc%3d", "type":"frisbee"},
{"name":"Bullet", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=bNPWBAZb4soUfVf4CdZoTmkOKZtHB%2fSab%2bF5jGNb3FA%3d", "type":"frisbee"},
{"name":"Caliber", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=ifrOHuFValn60J8mR9BZuvdIc%2bl%2b8ylZoJOHuJhVP6o%3d", "type":"frisbee"},
{"name":"Carolina Reign", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=6q2LBikwRKNzRuM9%2fo6b71Z1vMAZTI2DTmM59%2fTA6Pc%3d", "type":"frisbee"},
{"name":"Cerberus", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=%2fYUcOiV98Py5FYtaORlPvu3X2kyfaaS6zVEVI%2frTxPE%3d", "type":"frisbee"},
{"name":"Charlotte Storm", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=SHFfHyM8kX9u6yVKIwf70Bfa7J9pUhe73vkG8%2bH9Mu4%3d", "type":"frisbee"},
{"name":"Chalice", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=NbC9HHBM89hOcIDb0WARRH6oNZd7lYqNAqdMw3FVe8M%3d", "type":"frisbee"},
{"name":"Chimney", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=FntPkfSJCfEy93oTIo%2byROObgB1iLwDjVHKj7CPs%2b60%3d", "type":"frisbee"},
{"name":"Choco Ghost House", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=Fwio3mGQGkojn5OAVxddpH3GwfpXaYaYe6i%2fARhU7pY%3d", "type":"frisbee"},
{"name":"Choice City Hops", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=uhkNn1dQ5vpIKxAQDxAspxLUjlllVs6CR0clBUjS5xE%3d", "type":"frisbee"},
{"name":"Citywide Special", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=Ha0SdVEMdm1srp%2fPZPnDT9gyeRoh%2by%2bUV3r%2fdQs3RPE%3d", "type":"frisbee"},
{"name":"Classy", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=8refkTBxUJqYKNqnwojWM7h77wMUUU08YE7v7rPgufo%3d", "type":"frisbee"},
{"name":"Climax", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=4Z5czYE%2fVX0l98bXSJ9Hp58z%2fEKMxjbnfj9JUxs7K%2fs%3d", "type":"frisbee"},
{"name":"Cloverleaf", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=ODwTV0Xx0kbWyNGCmD0dSfTZeWfeGRBmGbnw4cVO47I%3d", "type":"frisbee"},
{"name":"Clue", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=C3cdG4bUruwAq%2buKk7kZPPThOh9d5tBWUp30uqgSn2Y%3d", "type":"frisbee"},
{"name":"Cold Snap", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=y2WHNqtLOgUF4mriuG2ho7e5fVwEdLAIzlMXejiDEOg%3d", "type":"frisbee"},
{"name":"Colt", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=VwxMI2FJdi0W%2b7zL6JkhA%2brCZpS4L%2fdKB6jCSNVnCSk%3d", "type":"frisbee"},
{"name":"Columbus Cocktails", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=%2fkDjHyaB2ZmiVHR9R2PRSk4c9zKpDDddM7GASHMmHco%3d", "type":"frisbee"},
{"name":"Cosa Nostra", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=2d7Ur%2bH1qR1GqFqdkYliZE4Y3v8JE6sL66E%2bDmDF6rI%3d", "type":"frisbee"},
{"name":"Crackle", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=BK4JiXcMl26liC9aAdrObpGJ9UaIuN0RhwEK2w5m4H0%3d", "type":"frisbee"},
{"name":"Crash", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=%2bGG3vHBi1Y61GQWBWRhgpII4y6mLvR6BTsPypaHkKgk%3d", "type":"frisbee"},
{"name":"Crush", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=pCD5grmktasA13dj4PUeQAF9r5P0IbKaKtXiriScq7o%3d", "type":"frisbee"},
{"name":"Cufax", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=D2HQqgOWV%2fu9kmYGcTb4TyoRk5L4u023Ht1z0qkLfxY%3d", "type":"frisbee"},
{"name":"Cutthroat", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=h33olmg680ErcPI063q5Gxzl54fKQnZql%2bafGKvoo6I%3d", "type":"frisbee"},
{"name":"Dark or Light", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=bgOO%2f%2bTLDqXl9yxlXdboNq0a2aZwOUIOpNn95ucp5yg%3d", "type":"frisbee"},
{"name":"Darkwing", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=zjUxayWv88pc4%2bCgBIJ9UVqI9ZD6PYH1GR0u6%2fjCtBE%3d", "type":"frisbee"},
{"name":"Dead Reckoning", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=R5LUoyeK9EwV5MGlvJgFoyjXDkjXO%2bO3Foza7WTmg3s%3d", "type":"frisbee"},
{"name":"Deathsquad", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=AKOcIKjeMI9E3EzqDSroOD0z0ZqJ6xleNYrrg4Dps%2bU%3d", "type":"frisbee"},
{"name":"Defunct", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=xc%2fxImgmy7G7QYBIo2ZKIGBavBL2X2GPLm1TA6alCFM%3d", "type":"frisbee"},
{"name":"Deluge", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=sx5pNadGd2fBeTTcubObfMRd%2b4%2fFNudJmnQU69312lg%3d", "type":"frisbee"},
{"name":"Delta Breeze", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=e0dpgzT7w79DcHw5dEYwVVbon%2fWUoNxneS%2fexUgXzUQ%3d", "type":"frisbee"},
{"name":"Doppler Effect", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=IB8cro8pWaVTUX0HoOFFokwu5WIl7kFnuPjQm90Wp1I%3d", "type":"frisbee"},
{"name":"Dish", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=TY%2bSPRzAPIuWe1xxrd81fr9b3GMiUDsApqMqEnoMZpA%3d", "type":"frisbee"},
{"name":"Distelfink", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=fd7CCvNi6HJh0y3zvaraZDd4S4ecK6kz0BMR8Zmu0XI%3d", "type":"frisbee"},
{"name":"Dinosaur", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=uGdxStDhsqHR0kB%2bleibU98X%2bm08VDtVpHnLsBKPFiA%3d", "type":"frisbee"},
{"name":"Dragon Army", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=tyULRDxvHzxeeC7T1F74UICqJ%2bD6iZ%2faszynMbdEkSQ%3d", "type":"frisbee"},
{"name":"Dreadnought", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=ebHb4n1Zd8gUbQY7ZXFNdmOlPcudG27OVe%2fS1028Tgk%3d", "type":"frisbee"},
{"name":"Dumpster Fire", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=%2bZL%2fn8plxlAzlwtjQ1xgF%2bKM5XDxa%2fjEoCq%2f14HJAWw%3d", "type":"frisbee"},
{"name":"El Niño", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=lS0%2fxSM%2f0v0J0U5U3wM66I9M2uP2ChfoYA6EkZJ6b1k%3d", "type":"frisbee"},
{"name":"Encore", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=18Jh9tAZaURNNMwDQAWcI2dFrz2GIOe3tM9MGuYGRi4%3d", "type":"frisbee"},
{"name":"Enigma", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=yzx0X%2fzaZUGy1CsdT6QcKZhxEdLQIfn3FIRuW7OF%2br0%3d", "type":"frisbee"},
{"name":"Erec Plus", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=%2bZe25OuHKbNiYzUvRQvQY5ZXH3ymVCEKFCmsomUDoN8%3d", "type":"frisbee"},
{"name":"Enough Monkeys", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=3DWfACaUB%2fNyREeEnSfMXGZL7%2bKeDHbXcHAasE74HlM%3d", "type":"frisbee"},
{"name":"Fable", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=v7f%2fubPQDLWdFG8pqgkEpeNVA5oiVOW%2bnx9V8pOLU9g%3d", "type":"frisbee"},
{"name":"Fear and Loathing", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=9OHOMVaS5qwKwN8WqrllaV58VvDCUJsCTFMtMe9HZm4%3d", "type":"frisbee"},
{"name":"Fifth Element", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=j7Fc2MfL9dExrK7A371qBqpNKLVs6Ys7R1PrbAy6t8A%3d", "type":"frisbee"},
{"name":"Family Style", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=L3HSTQO2gd46iuDiB%2bhjxmUCebuXW6hcPp3b0Wq%2bQP0%3d", "type":"frisbee"},
{"name":"Filthy Gorgeous", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=Aua96l05nl1JyLevvZ%2fgkXJmvAO99uUwLuTd%2bv4hLcE%3d", "type":"frisbee"},
{"name":"Fireball", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=I5aG%2b8rmH0O%2bQFswplhnmYEXwK%2bc7kLjnO%2bAMjPcT10%3d", "type":"frisbee"},
{"name":"Firefly", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=Cztb3d%2fukr%2f2oFcmcfVvplIkaUKUAg7JW4wzPstqYyY%3d", "type":"frisbee"},
{"name":"Flash Flood", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=yPaEDnnvSM73V05Ie13QUcVjGk8C%2bsZyAMT%2bYYFFuCc%3d", "type":"frisbee"},
{"name":"Friday Night Couch", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=mE7L%2bfmDM9KLTY5x6tskU79NdleXjZQFMFg7V8dVL%2fQ%3d", "type":"frisbee"},
{"name":"Four", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=vVo3pOtnHoG%2f%2f%2b2ZD3ojysBaYnLLc%2buuv6%2fm4ytYncU%3d", "type":"frisbee"},
{"name":"Fire Emoji", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=YjSTbM7dOr3TED1o9Ib0y8MWTN4M%2fG53zwNV3JRAn%2bQ%3d", "type":"frisbee"},
{"name":"Freetail", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=13EhKh4h27LHrTt9kFSBFH49ZwJ5ViS%2bnWOZZVndV8Q%3d", "type":"frisbee"},
{"name":"Friday Night Couch", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=mE7L%2bfmDM9KLTY5x6tskU79NdleXjZQFMFg7V8dVL%2fQ%3d", "type":"frisbee"},
{"name":"Further", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=w3RIcJOPWvICCBfUbHSc2HKmOR4G%2frOJWDU4CrhA8g0%3d", "type":"frisbee"},
{"name":"Furious George", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=%2bG16%2bOnOtJcLrQTA1UfJdUEeagqS3nhlc05DWhhbEhY%3d", "type":"frisbee"},
{"name":"Garbage Plates", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=XQD8u4%2fjkuwxqiuu080nRspeYOd0nHXa5hDYJCS2l88%3d", "type":"frisbee"},
{"name":"Goose Lee", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=ncnGZh18RvjqIi17o%2f7ammkJNgnXdfBPCI7HgaCvHNg%3d", "type":"frisbee"},
{"name":"Grassburner", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=3CpFCb%2fCdNtyYJkxWeG8OH7KgkG5aFXPmvPJFhWJfnY%3d", "type":"frisbee"},
{"name":"General Strike", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=7yJN%2bx7iN7NghMY36lhN7Hmq4Q8wNIAGHp071nxCWug%3d", "type":"frisbee"},
{"name":"Green River Swordfish", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=A4iz4Hp6Dwk9bJiTCq2%2bDbF8fGUwg0Cd9RhGNrIE38E%3d", "type":"frisbee"},
{"name":"Green", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=a3q%2b5frlBpIqMEN%2byBa4m4Tzfglo7dCmC2lrLNlfVGE%3d", "type":"frisbee"},
{"name":"Guerrilla", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=x3C13KT%2fFu5Rm5Ah95mu1UIIYIokej%2f1y%2f2tl6F5jHc%3d", "type":"frisbee"},
{"name":"Haymaker", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=X4VT2m%2f2Z9CiauLEdOJgqWSwxtPV81ES1vPCkoXdo%2bg%3d", "type":"frisbee"},
{"name":"Helix", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=9VGxJk8%2bnmx0wOjIHuVsSwUijslwtpTqOyCVJSpxfHQ%3d", "type":"frisbee"},
{"name":"Hoax", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=W6KLsWvpi2Ga9LI6HnnWRu7GnGYRl%2f8j9jheJllPXQI%3d", "type":"frisbee"},
{"name":"Honey Bashfords", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=%2fkQN1iIXnzd6suF7YkQUhgQD8Ie7xQpFHC3WMzVM%2bIw%3d", "type":"frisbee"},
{"name":"Honey Pot", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=omm5EGgWy7%2bMxUAtR5Zu5IvCPcSeMCB0%2b9CPUQ57Vk4%3d", "type":"frisbee"},
{"name":"Hot Metal", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=NmUcA3XL521B4QcEk5sAXflWhx43wtje1eKqH6m5lGY%3d", "type":"frisbee"},
{"name":"Heavy Flow", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=TGPSyBTIUvlrABK0HI6hMP%2fglVmP%2frH0SmK3Ya%2b3jIU%3d", "type":"frisbee"},
{"name":"Happy Hour", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=XVSx9KVeILeOou9MgtlMwy9F97sDOlhxk0G79Fk6NqI%3d", "type":"frisbee"},
{"name":"Happy Valley", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=Mhxalz1oOf7rZG0OoMQnv3b065dKP81icSjSJT0LGNI%3d", "type":"frisbee"},
{"name":"Imperial", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=cF0afyVmtsv9ARJyrQjxfcCOHGCaMCeRtXsckh2i4UM%3d", "type":"frisbee"},
{"name":"Inferno", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=OLPOl3LbzV%2fBMUbVHbbrL50WFHU6ktE4GdxunX4UcIQ%3d", "type":"frisbee"},
{"name":"Infidel", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=8j2nCPRCGz9pWVGPglse0x7ITM4WNhXcOo97i%2b3lS2s%3d", "type":"frisbee"},
{"name":"Instant Karma", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=tR4mo2BnuI9sC1ZaSFR0EC%2f1kCIVrOr%2fTtSRB%2fJVvWc%3d", "type":"frisbee"},
{"name":"Interesting Tummy Birds", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=g7i395q62aANcDE7JweOg1T1BeaPHvkj9GMgFIRrtCM%3d", "type":"frisbee"},
{"name":"Identity Crisis", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=iulWKWmlDSaxJQiqK7nuNj4Yeh2c5%2bj1xMkxeITkFrE%3d", "type":"frisbee"},
{"name":"Jabba", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=Hv%2fZ7nj9Jav%2bqp%2b8tw%2bClEPUPW8kYo0%2fIHvp%2fu0dEdk%3d", "type":"frisbee"},
{"name":"Jinx", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=IY1H3huJinQQaZbs8w%2fuRTJcxv2ru4OXUni3hZv%2bG0M%3d", "type":"frisbee"},
{"name":"Kentucky Flying Circus", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=IBN1T%2b7wO7qaOTjqFr66GAlsyyf6d7sTEMf0gtw8%2bYw%3d", "type":"frisbee"},
{"name":"LouFriendly", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=SkKp81yB3EU%2ftd4MaMkzjx8ViUN%2brED1h4WByexWvoo%3d", "type":"frisbee"},
{"name":"Long Beach Legacy", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=sZ2chlcIOBCZWHcpMeBENUIl1RuI0YpKMZ5Konf4NIE%3d", "type":"frisbee"},
{"name":"Mad Udderburn", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=GKpa8Ehr3cm1BCMDiHhBdLg4%2bK8LE%2b9LYx6nxgCoC6Q%3d", "type":"frisbee"},
{"name":"Madd Dogg", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=Db3z4Vs8SvNYdBNNMxAGupzj%2b5aPipJdC4PUqs7zncw%3d", "type":"frisbee"},
{"name":"Maeve", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=QMmtZMAy50xW9tp%2bx8G%2fAK%2bTnR%2bhggl0VZCkGEYDw%2bk%3d", "type":"frisbee"},
{"name":"Malicious Intent", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=ytiq16xFGrDDm4Sm2lc2ilgEbnwA99HmFI7tYx6qfsQ%3d", "type":"frisbee"},
{"name":"Mango Tree", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=X4rXP4D3OIpX0KVv8ffoSGhiPlLejGFf8PXA2Zxv4ec%3d", "type":"frisbee"},
{"name":"Makeshift Returns", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=O0dDMGarPh3S2fQaavJHTSB935Sdb3M6h%2bxBIXDA%2bO0%3d", "type":"frisbee"},
{"name":"Martian School", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=XhZzJclUsr32CvHBDFG%2fxNwf0nc%2bBNAvz%2f5E0PQToB8%3d", "type":"frisbee"},
{"name":"Midnight Whiskey", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=DQblptDegmvUbab9eUg%2bYewsN9R9tdM%2fURCxe3KXKGM%3d", "type":"frisbee"},
{"name":"Minnesota Star Power", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=NASlqktQhieEe6lztl5c%2biLW%2f3uWFV9xLpftCwgPKnw%3d", "type":"frisbee"},
{"name":"Mishigami", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=G7hM2VyzWnxdvBmvGRniH5uIElj4tZ9prgByScLIxzc%3d", "type":"frisbee"},
{"name":"Mojo Jojo", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=07cjoFoUSzbw8zechpiQocoWrhBQgJpU2cNexJK0ETk%3d", "type":"frisbee"},
{"name":"Munch Box", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=vw%2bpHJzZtaRQmCrrzQqyA3KnGZmArH114ROvDFfiZRs%3d", "type":"frisbee"},
{"name":"Murmur", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=AoraymRVkfdjmRcc0y7amCRGmuAkA9%2f8esieCUuHq7E%3d", "type":"frisbee"},
{"name":"Mutiny", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=Jd4hLvuipPXG4BsBiKS5%2fs0IoaxHeL2bbByAYvKvCLk%3d", "type":"frisbee"},
{"name":"Mystik", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=cn8z9AEliPr1XdkoPBvUGlBsEdxyKtwLqRNiGW8CbLY%3d", "type":"frisbee"},
{"name":"Nassau", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=2zzfVTA2kjSpBQ4E1Z7AbKblEq4QE9T%2bf0ScF3%2f0AF8%3d", "type":"frisbee"},
{"name":"Oh My", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=5iiv9nuk9mqJtcO3Bbx6UYPdBhNuYDQIOtqxbUqaKlE%3d", "type":"frisbee"},
{"name":"Orbit", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=5sH%2b4TSQ3%2feTJ%2fEHCaCc%2bQDm4c6iG59IVGz1GQgpu9I%3d", "type":"frisbee"},
{"name":"Papa Bear", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=zLw9wTS4Yt9X5ItRv%2bdPrOxOEDdpde4wK8xA2KNKns4%3d", "type":"frisbee"},
{"name":"Pandatime", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=85mHrp9lD%2biIjGN705Qnru66iurWRA9ZrQz6MmL9KRU%3d", "type":"frisbee"},
{"name":"Phoenix", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=5n%2fmLngMNCQzAun07%2bqPjA%2flOBKzlmOLM4mIzW8o1Sc%3d", "type":"frisbee"},
{"name":"Phoenix Uprising", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=d%2fNYGge1VRn7BRzMz41%2f9k%2bMe9beffcXzFwsgQ3nVy4%3d", "type":"frisbee"},
{"name":"Pegasus", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=7IF3fp7%2ba%2bqjPhzCdWWP3p4Nim3RD3c6hpHfjfe8Las%3d", "type":"frisbee"},
{"name":"Pine Baroness", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=df%2fUzn9Ox1mVAzqlUtMBS6lnYGG51J6h7qhscU3sFkc%3d", "type":"frisbee"},
{"name":"Pink Pear", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=4ZIJCc33Nl1aImFGmh207nkW67mGfu0THO0i400g6Bs%3d", "type":"frisbee"},
{"name":"Possum", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=Y%2f1FL18EwVvgToC2rq1ZP9RS064aLx7l7gIQGuDLj1M%3d", "type":"frisbee"},
{"name":"Queen Cake", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=vkLgDyUtSUk3myyKFTQgh7XvAJR%2fu83bHQ0UeEx2Yng%3d", "type":"frisbee"},
{"name":"Rabblecaddy", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=7D%2fct%2bOUoCJMyufzaEayIVYFJjawuPiGWoNA4i6GO%2f8%3d", "type":"frisbee"},
{"name":"Rampage", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=9e%2bvhUxqIK9kwYGahBdf0PLeiRD7f2p1RXyo2kkXlnI%3d", "type":"frisbee"},
{"name":"Rainbow", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=ULJjSzl%2bqwdNIVcu6jx%2fNRK3Mbt3VwNCF5%2fbmb5YLco%3d", "type":"frisbee"},
{"name":"Rawhide", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=1S7AMLCcNSRV2A3YvoioFiiyX4cLPgndyUIjiN0kAh4%3d", "type":"frisbee"},
{"name":"Renegade", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=SovSaTrGIfhVHBDpvm5qphVEkmAeOqFv1UOoqVWLh7M%3d", "type":"frisbee"},
{"name":"Right Coast", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=mL7D5KVhm6K3ME%2bygW50EsX2f75lVDS%2bCS8IxwhJ8ws%3d", "type":"frisbee"},
{"name":"Rice Crispies", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=vJmoHXj2nEJ17cvKCyVcPjqTwycW2XhYvvFCdF9k1Gs%3d", "type":"frisbee"},
{"name":"Rogue Grimace", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=MTfjBvvJGILe4ivcFicCy4h7UywPdj2bngQ20aKVAg8%3d", "type":"frisbee"},
{"name":"Rush Hour", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=heJRBcyPI3Iqzgv82vfA2GJDYkFz3PTAb%2bKHJczAtbI%3d", "type":"frisbee"},
{"name":"Risky Business", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=3%2fZ4mdu0hXx7rZKB%2bhWdHNQgd%2fnmO69p7lBJjCS%2fh3E%3d", "type":"frisbee"},
{"name":"Roc Paper Scissors", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=b4TN0vZ0vINDFYg8ilnplmLNmUz8LXx1Fsrzu9HIxHI%3d", "type":"frisbee"},
{"name":"Rocket Lawnchair", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=CGaIqbUDGfbqI0SwxFdmHptfTgZXnm2ixhHf434C6WM%3d", "type":"frisbee"},
{"name":"Rougaroux", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=aqS%2bjuv3y4I%2bKecGWJGqnTiiva87V2Q96CdDSiqx0hM%3d", "type":"frisbee"},
{"name":"Rogue", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=jDP%2bQvLF5qLPpmiyFVxKL2BfQuPp%2bTdaeDil5T%2b3shc%3d", "type":"frisbee"},
{"name":"Rubix", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=P4OS6CAc6%2b1CVZC%2bk3gAYySV1l0DD0II9d7IVIFyQKk%3d", "type":"frisbee"},
{"name":"Scubarus", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=GazMlG%2fjopkYCEhc6OAPfI2mnvyUu6UMQYknRO%2f8ptc%3d", "type":"frisbee"},
{"name":"Sculpin", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=5mhj2ZpUkT4uPCpmyF%2fhi7dMascu2066cNlT%2fvj2pok%3d", "type":"frisbee"},
{"name":"Schweingeist", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=1MagdPLACnlEDeD6ZbpRSuGbCAnqZ%2fz6SlUEMmEGNow%3d", "type":"frisbee"},
{"name":"Serengeti", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=riA08pmZQH4rHbyU2N4RWDPVRsE6s4ES61648fHR6yU%3d", "type":"frisbee"},
{"name":"Sellout", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=%2fw6ShbYss%2b7aONru2yP8vku5qdpdA3BF2r0pZt%2brXUc%3d", "type":"frisbee"},
{"name":"Serial Crusher Theory", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=Hthg4sia%2bfbUwIkIGMmSqRWHen48oy8tQ2dWn3yBZXo%3d", "type":"frisbee"},
{"name":"Shrimp Boat", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=oH0hcfk65x27hXo1RAhlHj5bsQHNJpRJwV4U7dRWumo%3d", "type":"frisbee"},
{"name":"Sir Walter Rowdy", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=yNYaUoMfHs3DZkG60jcbkjLvTlCUn9Nrkx2VugxTPlY%3d", "type":"frisbee"},
{"name":"Snip Snip", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=vVavxm%2bVfl6fwm0WX%2fJPZ1cGkTlo%2fRNwmq3QiMtasj0%3d", "type":"frisbee"},
{"name":"Sour Mash", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=vgRkJzb%2fFlR89oB020zUGDCQNEEgUHKQTlSsQKS6MgI%3d", "type":"frisbee"},
{"name":"Solar Eclipse", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=lcrlWC1V%2bXLOgJwXMlgz5DBw88AgiAqu%2b%2fDZuJsEINM%3d", "type":"frisbee"},
{"name":"South Shore Line", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=v9kt59gWmEYbhMclFQlyGO9MKxeoKCM7cVWZgToVyOE%3d", "type":"frisbee"},
{"name":"Spirit Quest", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=HD8TMlgtfALtbqtvNlIZ2c6aqzhJXSFb1ebs%2f3x6WNw%3d", "type":"frisbee"},
{"name":"Steel", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=7AJr0eIwge9WzxLwY02rzXHSPIliR6BkAfeH3Dp5Va8%3d", "type":"frisbee"},
{"name":"Stackcats", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=zp1FK7GcWa1nk0ZLyAQZ5RJ4iTPXujqcjNUfBcKIvvA%3d", "type":"frisbee"},
{"name":"Suffrage", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=dBh3IBmtkuLdpfjhWCU5RIqCZzl6%2fP9yE%2bvBEG0ZJ5E%3d", "type":"frisbee"},
{"name":"Swan", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=pctgR7sGS2kus2lci2G9dKddERDIjQb0QRiokIWIW2E%3d", "type":"frisbee"},
{"name":"Superstition", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=kXICAsDWhVyix73PSHq8Iqq2fpi12VgmN%2b8H10PmIjM%3d", "type":"frisbee"},
{"name":"Sunken Circus", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=dXiPTp61fN%2br3z5c2%2f9THS%2b36e66KgTA0EKcJgESwOk%3d", "type":"frisbee"},
{"name":"Sureshot", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=VwVBtGBHEFAwWhNV6LB42CjuS7X8P7JpZq74SKEbMzI%3d", "type":"frisbee"},
{"name":"Sweet Action", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=SZQsIl6O40onTUZ970MKZUdn%2bcPND95%2b5e%2fA%2fauMPBE%3d", "type":"frisbee"},
{"name":"Syracuse Doom", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=43kZAZbIsO4VQFSrlT4U%2bctwS6Buk3wKXUqQCEekUbs%3d", "type":"frisbee"},
{"name":"Tabby Rosa", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=noJ%2fD74wDyZxMWhMXwW6%2fVgjoyZJfvu%2bwkY%2bB5JAZio%3d", "type":"frisbee"},
{"name":"Thundersnow", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=p95K%2blqjlWraTbbSgnSrpgaGhSZ5PFg2Nh2WNhC5xJc%3d", "type":"frisbee"},
{"name":"Tragic Magic", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=%2bOqz7mO5rYjLhW%2bTrcu%2b1eslehJRztm1nL2BGgMhg7U%3d", "type":"frisbee"},
{"name":"Venom", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=vtqLpyFoFJNIffnN7dXMR6E1hDDqQAC0u9MnB4Yb9yE%3d", "type":"frisbee"},
{"name":"Voodoo", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=gxZjj03zqJmPTGOSwBElVcgCbpyFUrFyGU5sJ9dmWfU%3d", "type":"frisbee"},
{"name":"Wild Card", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=gu%2fYz2LSyoM9EqZKG9M0h7bL9lSEVUfZxMd6hOgvJTo%3d", "type":"frisbee"},
{"name":"War Machine", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=LighyFaLtpF8%2fT5%2bRVqA3CbdTj4Y0k0nsNG3QzJ7EbU%3d", "type":"frisbee"},
{"name":"Toro", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=yy2RaA0dhQ%2bmTTYcjS7%2fyd0VEhN3gnVg2FlTG%2bZZ1zI%3d", "type":"both"},
{"name":"Nassau", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=2zzfVTA2kjSpBQ4E1Z7AbKblEq4QE9T%2bf0ScF3%2f0AF8%3d", "type":"both"},
{"name":"Rampage", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=9e%2bvhUxqIK9kwYGahBdf0PLeiRD7f2p1RXyo2kkXlnI%3d", "type":"both"},
{"name":"Dark Star", "url":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=89aH0MRZsBdlKBrzi3W0KFFq9YfGlO0XjQiYsiAvs5A%3d", "type":"both"}
];

var both = {
	"Toro":{"hurl":"https://en.wikipedia.org/wiki/1928_Kentucky_Derby", "furl":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=yy2RaA0dhQ%2bmTTYcjS7%2fyd0VEhN3gnVg2FlTG%2bZZ1zI%3d"},
	"Nassau":{"hurl":"https://en.wikipedia.org/wiki/1923_Kentucky_Derby", "furl":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=2zzfVTA2kjSpBQ4E1Z7AbKblEq4QE9T%2bf0ScF3%2f0AF8%3d"},
	"Dark Star":{"hurl":"https://en.wikipedia.org/wiki/Dark_Star_(horse)", "furl":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=89aH0MRZsBdlKBrzi3W0KFFq9YfGlO0XjQiYsiAvs5A%3d"},
	"Rampage":{"hurl":"https://en.wikipedia.org/wiki/1986_Kentucky_Derby", "furl":"http://play.usaultimate.org/teams/events/Eventteam/?TeamId=9e%2bvhUxqIK9kwYGahBdf0PLeiRD7f2p1RXyo2kkXlnI%3d"}
};